sudo: required
dist: xenial
language: cpp

cache:
  - ccache

services:
  - docker

env:
  global:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.8/bin/llvm-symbolizer
    - ASAN_OPTIONS=log_path=/tmp/sanitizer,log_exe_name=1
    - LSAN_OPTIONS=suppressions=$TRAVIS_BUILD_DIR/core/lsan.suppress
    - UBSAN_OPTIONS=suppressions=$TRAVIS_BUILD_DIR/core/ubsan.suppress,print_stacktrace=1
    - GCOV_PREFIX_STRIP=2                       # /build/bess in the container
    - GCOV_PREFIX=$TRAVIS_BUILD_DIR             # /build/bess/core/xx becomes $TRAVIS_BUILD_DIR/core/xx
    - FIFO_TEST_TIMEOUT=200  # milliseconds per loop - vs default of 20
    - secure: "O4tRaArnQy2DOYjkDnAOBxb2csVK16uVL5IEiid6TkwMnK25FrEFNYHNLtnOXMds4m/msRiqkSMaFvB4v+uckW1IZlgrX783uiuVO/GGki5s0iahIrXU7y3l8A9BV6UDP7fjOsePLBdkwCp2GtT+BtndudR1VNI9GuvcKHlIWY/uhftzvZqddJtufxNIrgPiwIe097vO41kQQ/AlMRsyTudKnjoB3QhLQwPpVUD/VJgJGWOAOjktTKoDXTtScfDIn7z5mFQGzi2Z5gAqbGWm1R4AsbcEFBNbm+Uqp7V24ms9fuRA3eluKMO0m95CVqXnUYYk8UquyHfH8q9ucOodBodW2s6MF8AXdOojBPTD8Va9YQKwuwL/Go40E4d+KoqLnPkWqsIjPdd0Uec5schGgE5LzYf8fz9nN7V86KCjW8iNQgK0RX+XR29mS1hny3IZUYKFnVYoX8PKTE5AyIOP7nPvQWZsEM9QmMLIaTatQKSkLau+PAV9MeSXngPhwHig7YMCPxkwOhu6ftS6FSklBs6r/IOTfrRoyWccRYwZ5m7MS+7tUn70nxmYloAV5ZLNARS93RgQjU0zK82r7I77KwDgOIiD5bsYbaJgUY3AXsM/wzQkF1+3R2iVAtJtdAz0tS/zpgckQKTXvk8q1nojEmx9SCOIvaep8FUt3OcAS0o="
  matrix:
    - VER_CXX=g++-8

before_install:
  # Reserve hugepages as early as possible, to avoid fragmentation
  - sudo sysctl -w vm.nr_hugepages=512
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - "docker pull nefelinetworks/bess_build:latest${TAG_SUFFIX} | cat"

install:
  - ./container_build.py kmod_buildtest
  - travis_wait 30 docker build -t nimbess/bess:latest .

before_script:
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge
  - export CXX="ccache $VER_CXX"
  - ccache -s

script:
  - docker run --privileged -v /tmp/bess/:/tmp/ -v /dev/hugepages:/dev/hugepages -it nimbess/bess:latest ./run_tests.sh

after_failure:
  - more /tmp/bess/bessd.*.INFO.* | cat      # dump all bessd log files
  - sudo more /tmp/sanitizer* | cat          # dump all sanitizer results

after_script:
  - ccache -s

deploy:
  # Push images to Dockerhub on merge to master
  - provider: script
    on:
      branch: master
    script: >
      bash -c '
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push nimbess/bess:latest;
      echo done'

