sudo: required
dist: bionic
language: cpp

cache:
  - ccache

services:
  - docker

env:
  global:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.9/bin/llvm-symbolizer
    - ASAN_OPTIONS=log_path=/tmp/sanitizer,log_exe_name=1
    - LSAN_OPTIONS=suppressions=$TRAVIS_BUILD_DIR/core/lsan.suppress
    - UBSAN_OPTIONS=suppressions=$TRAVIS_BUILD_DIR/core/ubsan.suppress,print_stacktrace=1
    - GCOV_PREFIX_STRIP=2                       # /build/bess in the container
    - GCOV_PREFIX=$TRAVIS_BUILD_DIR             # /build/bess/core/xx becomes $TRAVIS_BUILD_DIR/core/xx
    - FIFO_TEST_TIMEOUT=200  # milliseconds per loop - vs default of 20
    - secure: "SWSp26Mjdh6pZd/eIMYLlHaoGCaP2fR4WQBaI7RFhSQ/QXn8FRrx19K8mc7byquHINMQwd+aFBZfz2dWoMl9tWR5WTkesyw616fJSKYNwo/ve1MsiSj4doVszYzfioJKCCDcvSAbrPXjmMyNYJ2r6YZtk+ETY8pzYgpJ3PsmJ/3RbuVbDWHxoytaEHnpAs0Jd9IjCcRWQXfAE6uOGQWdDZmp4aZv73G9Q3GGBQ4WY69F/PkvQlz3OOeyFqCDRrCz+9G/eirS9t7aJKkvYvEi1tb1nKie8wwOFVrl/b+EfHXjU+2j82lYx7gvIV6aGSq/0OcknROk9XKfpynANrzbsVfCXBMBjxLv3UZxTBy8VUrv7dWHSsnsyw8UFDFWuyjAfNl4LQ5udBe8iSepYZvKJ9qeFUCzcFOvesUmaARfhq74CVqQPkI9/lddQe7Y/n9DXgCV0VrPT4JhGXQ/Gj1yDUDvJl4HOkxjxZrxQ0AZ86Hr6TSUlnfL9dHmMgzxEYD7tbZn1XF6gZK4+HRhmT6G7JDeM5W2wWemyDorW/4kncwnaKDm3RQ6e6gNsrSthjRWI3eXcgap5XS6d/bTErWESD+J8sqpSriiyjw2y8sMoG0w4jDHrp4n2F9VV/AOAbBJzlHGwVoV7QZbIGjDCqhgN2Uy/y6EkBdiARp1rAsOpRs="
  matrix:
    - VER_CXX=g++-8

before_install:
  # Reserve hugepages as early as possible, to avoid fragmentation
  - sudo sysctl -w vm.nr_hugepages=512
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - "docker pull nefelinetworks/bess_build:latest${TAG_SUFFIX} | cat"

install:
  - ./container_build.py kmod_buildtest
  - travis_wait 35 docker build -t nimbess/bess:latest .

before_script:
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge
  - export CXX="ccache $VER_CXX"
  - ccache -s

script:
  - docker run --privileged -v /tmp/bess/:/tmp/ -v /mnt/huge:/dev/hugepages -it nimbess/bess:latest ./run_tests.sh

after_failure:
  - more /tmp/bess/bessd.*.INFO.* | cat      # dump all bessd log files
  - sudo more /tmp/sanitizer* | cat          # dump all sanitizer results

after_script:
  - ccache -s

deploy:
  # Push images to Dockerhub on merge to master
  - provider: script
    on:
      branch: k8-development
    script: >
      bash -c '
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push nimbess/bess:latest;
      echo done'

